Added missing perl-generators package
perl-generators is needed for building the new packages and on some systems it may need to be explicitly installed:

```
Building RPMS... it may take a while
error: Failed build dependencies:
	perl-generators is needed by rdma-core-54mlnx1-54311.versatushpc.x86_64
```